"use client";
import React, { Component, type ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { liveEventSchema, type ConnectionState, type DataFreshness, type PublicSignal, type Snapshot } from "../../../lib/live/contracts";
type CommonProps = { initialData?: unknown; liveUpdates?: unknown; loading?: boolean; stale?: boolean; error?: string; disabled?: boolean; empty?: boolean; reducedMotion?: boolean; accessibilityLabel?: string; freshness?: DataFreshness };
const freshnessText = (f?: DataFreshness) => f?.state === "unavailable" ? "Temporarily unavailable" : f?.state === "stale" ? "Stale data" : f?.state === "cached" ? "Cached" : f?.state === "estimated" ? "Estimate" : f?.state === "live" ? "Live now" : "Recently measured";
export function LiveConnectionIndicator({ state }: { state: ConnectionState }) { return <span className={`liveIndicator state${state}`} role="status"><i aria-hidden="true" />{state === "DISABLED" ? "Live features disabled" : state}</span>; }
export function LiveDataBadge({ freshness, accessibilityLabel = "Data freshness" }: CommonProps) { return <span className="liveBadge" aria-label={accessibilityLabel}>{freshnessText(freshness)}</span>; }
export function LastUpdatedLabel({ freshness }: CommonProps) { const time = freshness?.receivedAt ?? freshness?.measuredAt; return <time dateTime={time}>{time ? `Updated ${new Date(time).toLocaleString()}` : "No verified update available"}</time>; }
export function StaleDataNotice({ stale, freshness }: CommonProps) { return stale || freshness?.state === "stale" ? <p className="staleNotice" role="status">Updates are delayed. Showing the last verified snapshot.</p> : null; }
export function LiveReconnectButton({ onClick }: { onClick: () => void }) { return <button className="liveControl" type="button" onClick={onClick}>Retry connection</button>; }
export function LiveStreamToggle({ enabled, onChange }: { enabled: boolean; onChange: (v: boolean) => void }) { return <button className="liveControl" type="button" aria-pressed={enabled} onClick={() => onChange(!enabled)}>{enabled ? "Disable live updates" : "Enable live updates"}</button>; }
export const LiveDataConsentControl = LiveStreamToggle;
export function LiveMetricCard({ accessibilityLabel = "Live metric", disabled, empty, error, freshness, children }: CommonProps & { children?: ReactNode }) { return <article className="liveCard" aria-label={accessibilityLabel}>{error ? <p>{error}</p> : disabled ? <p>Stream disabled</p> : empty ? <p>No verified data</p> : children}<LiveDataBadge freshness={freshness} /></article>; }
export function LiveSignalGrid({ children, accessibilityLabel = "Signal grid" }: CommonProps & { children?: ReactNode }) { return <section className="liveGrid" aria-label={accessibilityLabel}>{children}</section>; }
export function LiveActivityTimeline({ children, accessibilityLabel = "Activity timeline" }: CommonProps & { children?: ReactNode }) { return <ol aria-label={accessibilityLabel}>{children}</ol>; }
export function LiveStatusBanner({ initialData, freshness }: CommonProps) { const signal = initialData as PublicSignal | undefined; return <aside className="liveStatusBanner"><b>ClearGlass Live Signal Fabric</b><span>{signal?.message ?? "No verified status available"}</span><LiveDataBadge freshness={freshness} /></aside>; }
export const LivePerformancePanel = LiveMetricCard; export const LiveSystemMap = LiveSignalGrid; export const LiveEventStream = LiveActivityTimeline;
export class LiveErrorBoundary extends Component<{ children: ReactNode }, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; } render() { return this.state.failed ? <aside className="staleNotice" role="alert">Live module unavailable. Static content remains available. <button type="button" onClick={() => this.setState({ failed: false })}>Retry</button></aside> : this.props.children; } }
export function LivePageShell({ initialSnapshot, children }: { initialSnapshot: Snapshot; children: ReactNode }) {
 const [snapshot,setSnapshot]=useState(initialSnapshot), [enabled,setEnabled]=useState(initialSnapshot.enabled), [state,setState]=useState<ConnectionState>(initialSnapshot.enabled?"CONNECTING":"DISABLED"), [attempt,setAttempt]=useState(0); const lastId=useRef(initialSnapshot.lastEventId), seen=useRef(new Set<string>());
 const refresh=useCallback(async()=>{try{const r=await fetch(`/api/live/snapshot?stream=${encodeURIComponent(snapshot.stream)}`,{cache:"no-store"});if(!r.ok)throw new Error();const n=await r.json() as Snapshot;setSnapshot(n);setState(n.enabled?"DEGRADED":"DISABLED");}catch{setState(navigator.onLine?"ERROR":"OFFLINE");}},[snapshot.stream]);
 useEffect(()=>{if(!enabled||document.visibilityState==="hidden")return;let source:EventSource|undefined,timer:ReturnType<typeof setTimeout>|undefined;const connect=()=>{setState("CONNECTING");source=new EventSource(`/api/live/${snapshot.stream}${lastId.current?`?lastEventId=${encodeURIComponent(lastId.current)}`:""}`);source.onopen=()=>{setState("LIVE");setAttempt(0)};source.onmessage=(m)=>{let json:unknown;try{json=JSON.parse(m.data)}catch{return}const p=liveEventSchema.safeParse(json);if(!p.success||seen.current.has(p.data.id))return;seen.current.add(p.data.id);lastId.current=p.data.id;setSnapshot(c=>({...c,signal:p.data.payload,lastEventId:p.data.id}))};source.onerror=()=>{source?.close();const n=attempt+1;setAttempt(n);setState(n>=6?"DEGRADED":"CONNECTING");if(n>=6)void refresh();else timer=setTimeout(connect,Math.min(30000,1000*2**attempt)*(.8+Math.random()*.4))}};connect();const offline=()=>setState("OFFLINE"),online=()=>{setAttempt(0);connect()};window.addEventListener("offline",offline);window.addEventListener("online",online);return()=>{source?.close();if(timer)clearTimeout(timer);window.removeEventListener("offline",offline);window.removeEventListener("online",online)}},[attempt,enabled,refresh,snapshot.stream]);
 return <LiveErrorBoundary><div className="liveGlobalBar" aria-live="polite"><LiveConnectionIndicator state={state}/><LastUpdatedLabel freshness={snapshot.signal.freshness}/><LiveStreamToggle enabled={enabled} onChange={(v)=>{setEnabled(v);setState(v?"CONNECTING":"DISABLED")}}/><button className="liveControl" type="button" onClick={refresh}>Refresh snapshot</button></div>{children}<noscript><aside className="staleNotice">Live updates require JavaScript. Server-rendered content remains available.</aside></noscript></LiveErrorBoundary>;
}
