name: Auto Heal

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  heal:
    uses: ClearGlasslabs/workflow-artifacts/.github/workflows/reusable-auto-heal.yml@3b471303b256ad571448d58d9c81a411a828c3c4
    with:
      run_id: ''
